defmodule Realworld.Repo.Migrations.CreateDurableObjects do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:durable_objects, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:description, :text)
      add(:code_content, :text, null: false)
      add(:api_schema, :text, default: "")
      add(:version, :bigint, default: 1)
      add(:status, :text, default: "draft")
      add(:last_modified, :utc_datetime, default: fragment("(now() AT TIME ZONE 'utc')"))
      add(:modification_history, {:array, :map}, default: [])
      add(:deployment_history, {:array, :map}, default: [])
      add(:rollback_history, {:array, :map}, default: [])
    end
  end

  def down do
    drop(table(:durable_objects))
  end
end
